spring:
  application:
    name: seata-rest-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8890
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: spring-cloud://127.0.0.1
  scan:
    base-packages: com.cly.springcloud.*
  cloud:
    subscribed-services: seta-account-provider,seta-order-provider,seta-repo-provider
seata:
  #是否开启spring-boot自动装配
  enabled: true
  tx-service-group: my_test_tx_group
  transport:
    type: TCP
    server: NIO
    #client和server通信心跳检测开关
    heartbeat: true
    #客户端事务消息请求是否批量合并发送,默认true，false单条发送
    enable-client-batch-send-request: true
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      boss-thread-size: 1
      worker-thread-size: 8
    shutdown:
      wait: 3
    #client和server通信编解码方式
    serialization: seata
    #client和server通信数据压缩方式
    compressor: none
  service:
    vgroup-mapping:
      my_test_tx_group: default
    enable-degrade: false
    disable-global-transaction: false
    #grouplist: 192.168.216.128:8091
  client:
    rm:
      lock:
        #校验或占用全局锁重试间隔	默认10，单位毫秒
        lock-retry-interval: 10
        #分支事务与其它全局回滚事务冲突时锁策略	默认true，优先释放本地锁让回滚成功
        lock-retry-policy-branch-rollback-on-conflict: true
        #校验或占用全局锁重试次数
        lock-retry-times: 30,默认30
        #异步提交缓存队列长度	默认10000。 二阶段提交成功，RM异步清理undo队列
      async-commit-buffer-limit: 10000
      #一阶段结果上报TC重试次数	默认5次
      report-retry-count: 5
      #自动刷新缓存中的表结构	默认false
      table-meta-check-enable: false
      #是否上报一阶段成功	true、false，从1.1.0版本开始,默认false.true用于保持分支事务生命周期记录完整，false可提高不少性能
      report-success-enable: true
    tm:
      #一阶段全局提交结果上报TC重试次数	默认1次，建议大于1
      commit-retry-count: 5
      #一阶段全局回滚结果上报TC重试次数	默认1次，建议大于1
      rollback-retry-count: 5
#    rm-async-commit-buffer-limit: 10000
#    rm-report-retry-count: 5
#    rm-table-meta-check-enable: false
#    rm-report-success-enable: true
#    tm-commit-retry-count: 5
#    tm-rollback-retry-count: 5
    undo:
#      undo-log-table: undo_log
#      undo-data-validation: true
#      undo-log-serialization: jackson
      #自定义undo表名	默认undo_log
      log-table: undo_log
      #二阶段回滚镜像校验	默认true开启，false关闭
      data-validation: true
      #undo序列化方式	默认jackson
      log-serialization: jackson
    log:
      exception-rate: 100
    support:
      spring:
        datasource-autoproxy: false
#  registry:
#    type: nacos
#    nacos:
#      cluster: default
#      server-addr: 127.0.0.1:8848
